[tool.poetry]
name = "grafica-coxabengoa"
version = "0.1.0"
description = ""
authors = ["Horacio"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dash = "^2.18.0"
plotly = "^5.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
